

# This file was *autogenerated* from the file hw3_inverse.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0)
import sys

if len(sys.argv) <= _sage_const_1 :
    print("Use this file like this: sage hw3_inverse.sage 16")
    exit()

R = Integers(int(sys.argv[_sage_const_1 ])) 

units = [x for x in R if x.is_unit()]
zero_divisors = [y for y in R if y != _sage_const_0  and not y.is_unit()]
print("Unit group:", units)
print("Zero divisors:", zero_divisors)

